--- 
postMerge: 
  preRun: 
    command: 
      - "yarn install"
  subModules: 
    - 
      framework: jest
      name: popmotion
      path: ./packages/popmotion
      pattern: 
        - ./src/**/__tests__/*.test.ts
    - 
      framework: jest
      name: framesync
      path: ./packages/framesync
      pattern: 
        - ./src/_tests/test.ts
    - 
      framework: jest
      name: projection
      path: ./packages/projection
      pattern: 
        - ./src/__tests__/*test.ts
    - 
      framework: jest
      name: style-value-types
      path: ./packages/style-value-types
      pattern: 
        - ./src/_tests/*.ts
tier: medium
version: "2.0.1"
