postMerge :
  preRun: 
    command:
      - yarn install
  subModules:    
      - name: framesync
        path : "./packages/framesync/"
        pattern: 
          - "./src/_tests/test.ts"
        framework : jest

      - name:  popmotion
        path : "./packages/popmotion"
        pattern: 
          - "./src/**/__tests__/*.test.ts"
        framework : jest
       
version : 2.0.0
tier: large
